// Import Libraries
import Head from 'next/head'

// Home Component
export default function Home() {
  return (
    <>
      <Head>
        <title>IRCTC | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        HOME PAGE
      </main>
    </>
  )
}
