suspected_rfi = {
    #HIGH TAGS
    'SUS_EMAIL_IP_MORE_5' : 'UA1',
    'GIBBERISH_EMAIL' : 'UA1',
    'DISPOSABLE_EMAIL' : 'UA2',
    'SUS_USERNAME_IP_MORE_5' : 'UA3',
    'GIBBERISH_USERNAME' : 'UA3',
    'SUS_REG_TIME_60' : 'UA4',
    'SUS_REG_TIME_WITHIN_60_SEC' : 'UA4',
    "4_USER_REGISTERED_USING_VPS_AND_SAME_IP_POOL" : 'UA5',
    "SAMEIP_MORE4_VPS" : 'UA6',
    "4_PNR_BOOKED_USING_VPS_AND_SAME_IP_POOL" : 'UA7',

    #MEDIUM TAGS
    'SUSPICIOUS_FULLNAME' : 'UB1',
    'SUSPICIOUS_ADDRESS' : 'UB2',
    'USER_REG_SAMEIP_SAMEADDR_MORE_4' : 'UB2',
    'UNVERIFIED_USER' : 'UB3',
    "SERIES_USERNAME" : 'UB4',
    "5_PNR_BOOK_SAMEIP_SAMEDAY" : 'UB5',
    "5_PNR_BOOK_SAMEIP_60SEC" : 'UB6',
    "TEMPORARY_NUMBER" : 'UB7',
    'USER_REG_SERIES_COMMON_NAME' : 'UB8',

    #LOW TAGS
    'SUS_FULLNAME_IP_MORE_5' : 'UC1',
    'GIBBERISH_FULLNAME' : 'UC1',
    'GIBBERISH_ADDRESS' : 'UC2',
    'SUS_ADDRESS_IP_MORE_5' : 'UC2',
    'USER_BOOK_MULTIPLE_IP' : 'UC3',
    'USER_REG_SERIES_NONVPS' : 'UC4',
    'USER_REG_SERIES_VPS' : 'UC5',
    'USER_BOOK_VPS' : 'UC6',
    'USER_SERIES_BOOK_VPS' : 'UC7',
    'USER_SERIES_BOOK_NONVPS' : 'UC8',
    'USER_REG_VPS' : 'UC9',
    'USER_SERIES_REG_NONVPS' : 'UC10',
    'USER_SERIES_REG_VPS' : 'UC11',
    'BOOKING_IP_VPS' : 'UC12',
    'REG_MORE_THAN_5' : 'UC13',
    'TK_MORE_THAN_20_AC' : 'UC14',
    'TK_MORE_THAN_20_ARP' : 'UC15',
    'TK_MORE_THAN_20_NON_AC' : 'UC16',
    'USER_REG_SERIES_EMAIL' : 'UC17',
    "USER_REG_BOOK_VPS" : "UC18",
    "USED_BY_SUSPICIOUS_USER" : "UC19", 
    "INVALID_PINCODE" : "UC20",
    "USER_BOOK_SUSPICIOUS_MOBILE":"UC21",
    "SUSPICIOUS_IP":"UC22",
    "SUSPICIOUS_USER":"UC23",
    "INVALID_BOOKING_MOBILE":"UC24",
    "INVALID_REGISTERED_MOBILE":"UC25"
}

mappingDictionary = {
    'BOOKING_IP_VPS' : 'IP Address used VPS to book ticket',
    'REG_MORE_THAN_5' : 'IP Address used to register more than 5 users',
    'TK_MORE_THAN_20_AC' : 'More than 20 tickets booked using same IP',
    'TK_MORE_THAN_20_ARP' : 'More than 20 tickets booked using same IP',
    'TK_MORE_THAN_20_NON_AC' : 'More than 20 tickets booked using same IP',
    "USER_REG_BOOK_VPS" : "VPS used to book ticket",
    "USED_BY_SUSPICIOUS_USER" : "Suspicious User",
    "SUSPICIOUS_IP" : "Suspicious IP",
    "SUSPICIOUS_USER" : "Suspicious User",
    "INVALID_BOOKING_MOBILE" : 'Invalid Mobile number used to book ticket',
    'USER_REG_SERIES_EMAIL':'Username registered from suspicious Email',
    'SUS_EMAIL_IP_MORE_5' : 'User registered with a gibberish email',
    'SUS_USERNAME_IP_MORE_5' : 'User registered with a gibberish username',
    'SUS_ADDRESS_IP_MORE_5' : 'User registered with a suspicous address',
    'SUS_FULLNAME_IP_MORE_5' : 'User registered with a suspicous fullname',
    'USER_BOOK_MULTIPLE_IP': 'Multi-IP Bookings',
    'USER_SERIES_REG_NONVPS': 'Username is a part of series, registered from NONVPS',
    'USER_REG_SERIES_NONVPS': 'Username is a part of series, registered from NONVPS',
    'USER_REG_VPS': 'User has been registered from a VPS IP Address',
    'USER_REG_SERIES_VPS' :'User has been registered from a VPS IP Address',
    'USER_SERIES_REG_VPS': 'Username part of series, registered from vps',
    'USER_BOOK_SUSPICIOUS_MOBILE': 'Suspicious Booking Mobile Number',
    'USER_BOOK_VPS': 'VPS Booking',
    'USER_REG_IP_ADDR_SAME_MORE_4': 'Duplicate Address',
    'USER_SERIES_BOOK_NONVPS':'User Series Booking',
    'USER_SERIES_BOOK_VPS':'User Series Booking',
    'USER_REG_SAMEIP_SAMEADDR_MORE_4': 'More than 4 Users Registered During with Same IP and Address',
    'USER_REG_SERIES_COMMON_NAME': 'Registered in Series of Common Name of More than 15',
    'SUS_REG_TIME_WITHIN_60_SEC': "Registered more than 2 times through same ip within 60 sec",
    "INVALID_PINCODE":"Invalid pincode",
    "INVALID_REGISTERED_MOBILE":"Invalid registered mobile",
    "SERIES_USERNAME" : "PNR booked with a Series of Username", 
    "5_PNR_BOOK_SAMEIP_60SEC" : "More than 5 PNR booked through the same IP address within 60 seconds",
    "5_PNR_BOOK_SAMEIP_SAMEDAY" : "More Than 5 PNR booked with same IP address in same day",
    "SAMEIP_MORE4_VPS" : "PNR booked using Same VPS IP more than 4 times",
    "TEMPORARY_NUMBER" : "PNR Booked using Suspicious Number",
    'GIBBERISH_EMAIL' : "User Registered with an Email in series",
    'DISPOSABLE_EMAIL' : "User registered with a disposable Email Domain",
    'GIBBERISH_USERNAME' : "User Registered with a Username in series",
    'SUS_REG_TIME_60' : "More than 4 Users Registered through the same IP address within 60 seconds",
    'SUSPICIOUS_FULLNAME' : "More than 5 Users Registered with Same Full name and IP Address",
    'SUSPICIOUS_ADDRESS' : "More than 5 Users Registered with Same Physical Address and IP Address",
    'UNVERIFIED_USER' : "Unverified User",
    'GIBBERISH_FULLNAME' : "User registered with a Fullname in series",
    'GIBBERISH_ADDRESS' : "User registered with a Address in series",
    "4_PNR_BOOKED_USING_VPS_AND_SAME_IP_POOL" : "More than 4 PNR booked using VPS and same IP pool",
    "4_USER_REGISTERED_USING_VPS_AND_SAME_IP_POOL" : "More than 4 users registered using VPS and same IP pool"
}